### PR TITLE
Please  review and merge my changes into cbracco

### PR DESCRIPTION
**Pull request by ModernTek**

### CODE REVIEW

**Comment by cbracco** [comment]
Hi @ModernTek! I cleaned up some of the spacing/formatting a bit, and merged this into `master`. 

I have some comments/feedback:
- Nice job on the popovers! I changed them a bit, moving the base styles onto the `.popover` class, so you add two classes now to the base HTML element (one for the base styles `.popover`, and another to determine the direction e.g. `.popover-top`).
- With the waves, I’m not sure what you created is what they were looking for. The ["Wave" component in Materialize.css](materializecss.com/waves.html) is the animation that occurs when you click on a button. I found a [simple CSS-only version](https://ghinda.net/article/css-ripple-material-design/) of this that you could use as a starting point, if you’d like to try again on this one. If not, I can build it, or we can do it together. Let me know what you would like to do.

Thanks for contributing!

**Comment by ModernTek** [comment]
Hi Chris,I have started to work on the wave, based on article that you pointed out.I did something, but I do not to commit to git. Do you think we need to delete my old "wave" and added this new one?

**Comment by ModernTek** [comment]
Hi Chris, Thank you very much for being patient with me. I have struggling with materialize waves Yesterday and decided just create any waves. I am interested to do CSS-only version. I would like to build it together, since I have never used @keyframes and animation. I just learning about it now. I have EST time zone. I am available after 5:00 pm EST or I can do early in the morning around 7:00 am EST, because I am working full time. However, in the morning I will not have maybe enough time.Let me know when you are available? I do not know what is your time zone. Thanks Natalie

**Comment by ModernTek** [comment]
Hi Chris, I was trying to commit directly to cbracco branch and I was not able to do so. I do not understand why, because, now cbracco master branch shows me as contributor. Therefore, I have created pull request. Let me know, if you would like to work on this. Thanks Natalie

**Comment by ModernTek** [comment]
Hi Chris, I have not heard from you, so I have decided to change wave.css and index.html any way, based on article a simple CSS-only-version. I did not complete the task, but that's what I have so far. I was not able to push to cbracco repository (error 403), therefore I have pushed to ModernTek repository. I am going to issue pull request and you can see what I did. If you can find time, we can complete it together. Thanks Natalie

**Comment by cbracco** [comment]
@ModernTek Ok I will check your pull request.

**Pull request merged**
